import streamlit as st
import pandas as pd
import plotly.express as px
import json
import io
import os
import tempfile
from datetime import datetime
from fpdf import FPDF

from utils import authenticate_user, create_user

st.set_page_config(page_title="Crime Pattern Dashboard", layout="wide")

# Initialize session state
if "logged_in" not in st.session_state:
    st.session_state.logged_in = False
if "username" not in st.session_state:
    st.session_state.username = ""
if "role" not in st.session_state:
    st.session_state.role = ""

# Ensure users.json exists
if not os.path.exists("users.json"):
    with open("users.json", "w") as f:
        json.dump({
            "users": [
                {"username": "public", "password": "public123", "role": "public"},
                {"username": "analyst", "password": "analyst123", "role": "analyst"},
                {"username": "law", "password": "law123", "role": "law_enforcement"}
            ]
        }, f, indent=2)


def save_plotly_as_image(fig):
    try:
        tmpfile = tempfile.NamedTemporaryFile(delete=False, suffix=".png")
        fig.write_image(tmpfile.name, format="png", engine="kaleido")
        return tmpfile.name
    except Exception as e:
        st.warning(f"❌ Chart export failed: {e}. Chart will be omitted from PDF.")
        return None


def generate_pdf_report(df, username, chart_paths):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", "B", 16)
    pdf.cell(0, 10, "Crime Report Summary", ln=1, align="C")
    pdf.set_font("Arial", size=12)
    pdf.ln(2)
    pdf.cell(0, 8, f"Generated by: {username}", ln=1)
    pdf.cell(0, 8, f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", ln=1)
    pdf.ln(5)

    # Summary stats
    pdf.set_font("Arial", "B", 14)
    pdf.cell(0, 8, "Crime Type Counts:", ln=1)
    pdf.set_font("Arial", size=12)
    summary = df["crime_type"].value_counts().reset_index()
    summary.columns = ["crime_type", "count"]
    for _, row in summary.iterrows():
        pdf.cell(0, 6, f"{row['crime_type']}: {row['count']}", ln=1)
    pdf.ln(5)

    # Add charts if available
    for path in chart_paths:
        if path and os.path.exists(path):
            try:
                pdf.image(path, w=180)
                pdf.ln(5)
            except Exception:
                pass

    # Return bytes
    pdf_bytes = io.BytesIO()
    pdf_output = pdf.output(dest="S").encode("latin-1")
    pdf_bytes.write(pdf_output)
    pdf_bytes.seek(0)
    return pdf_bytes


def show_login():
    st.markdown(
        """
        <div style="max-width:420px; margin:auto; padding:2rem; background:#f5f7fa; border-radius:12px; box-shadow:0 10px 30px rgba(0,0,0,0.05);">
            <h2 style="text-align:center; color:#1f77b4;">Login</h2>
            <p style="text-align:center; margin-top: -10px;">Enter credentials to access the dashboard</p>
        </div>
        """,
        unsafe_allow_html=True,
    )

    col1, col2, col3 = st.columns([1, 2, 1])
    with col2:
        username = st.text_input("Username")
        password = st.text_input("Password", type="password")
        role_select = st.selectbox("Role", ["public", "analyst", "law_enforcement"])
        if st.button("Login"):
            role = authenticate_user(username, password)
            if role and role == role_select:
                st.session_state.logged_in = True
                st.session_state.username = username
                st.session_state.role = role
                st.success(f"Logged in as {username} ({role})")
                try:
                    st.experimental_rerun()
                except AttributeError:
                    pass
            else:
                st.error("Invalid credentials or role mismatch.")

    st.markdown("---")
    st.subheader("New User Signup")
    new_username = st.text_input("New Username", key="signup_user")
    new_password = st.text_input("New Password", type="password", key="signup_pass")
    new_role = st.selectbox("Select Role", ["public", "analyst", "law_enforcement"], key="signup_role")
    if st.button("Sign Up"):
        if not new_username or not new_password:
            st.warning("Provide both username and password.")
        else:
            success = create_user(new_username, new_password, new_role)
            if success:
                st.success("Account created. Please log in.")
            else:
                st.error("Username already exists.")


def show_dashboard():
    role = st.session_state.role
    st.sidebar.markdown(f"*Logged in as:* {st.session_state.username} ({role})")
    if st.sidebar.button("Logout"):
        st.session_state.logged_in = False
        st.session_state.username = ""
        st.session_state.role = ""
        try:
            st.experimental_rerun()
        except AttributeError:
            pass
        return

    st.title("🚔 Crime Pattern Analysis Dashboard")

    uploaded_file = st.file_uploader(
        "Upload Crime Data File (CSV or Excel)",
        type=["csv", "xlsx", "xls"],
    )

    if uploaded_file is None:
        st.info(
            "Please upload a CSV or Excel file with columns: date, crime_type, latitude, longitude."
        )
        return

    try:
        fname = uploaded_file.name.lower()
        if fname.endswith(".csv"):
            df = pd.read_csv(uploaded_file)
        elif fname.endswith((".xls", ".xlsx")):
            df = pd.read_excel(uploaded_file)
        else:
            st.error("Unsupported file type.")
            return
    except Exception as e:
        st.error(f"Failed to read file: {e}")
        return

    df.columns = df.columns.str.lower()
    required = {"date", "crime_type", "latitude", "longitude"}
    if not required.issubset(df.columns):
        st.error("File must contain: date, crime_type, latitude, longitude")
        return

    # Preprocessing
    df = df.drop_duplicates()
    try:
        df["date"] = pd.to_datetime(df["date"], errors="coerce")
    except Exception:
        pass
    df = df.dropna(subset=["date", "latitude", "longitude", "crime_type"])

    # Filters
    # Crime type filter
    if "crime_type" in df.columns:
        crime_types = st.sidebar.multiselect(
            "Crime Type",
            sorted(df["crime_type"].dropna().unique()),
            default=sorted(df["crime_type"].dropna().unique()),
        )
        if crime_types:
            df = df[df["crime_type"].isin(crime_types)]

    # Date range filter
    if "date" in df.columns:
        date_range = st.sidebar.date_input(
            "Date Range",
            [df["date"].min().date(), df["date"].max().date()],
        )
        if len(date_range) == 2:
            start, end = date_range
            df = df[(df["date"].dt.date >= start) & (df["date"].dt.date <= end)]

    # Time (hour) filter
    if "date" in df.columns:
        df["hour"] = df["date"].dt.hour
    unique_hours = df["hour"].dropna().unique()
    if len(unique_hours) > 1:
        min_hour, max_hour = int(df["hour"].min()), int(df["hour"].max())
        hour_range = st.sidebar.slider(
            "Hour Range",
            min_hour,
            max_hour,
            (min_hour, max_hour),
            step=1,
        )
        df = df[(df["hour"] >= hour_range[0]) & (df["hour"] <= hour_range[1])]
    else:
        st.sidebar.info(f"All records are hour {unique_hours}. No hour filter applied.")



    # Region (city/district/region) filter
    possible_region_cols = [
    col for col in df.columns if col.lower() in ["region", "city", "district"]
]
if possible_region_cols:
    region_col = possible_region_cols   # Always get only the column name
    unique_regions = sorted(df[region_col].dropna().unique())
    selected_regions = st.sidebar.multiselect(
        "Region", unique_regions, default=unique_regions
    )
    df = df[df[region_col].isin(selected_regions)]


    # Views by role
    if role == "public":
        st.info("Public View: aggregated summary")
        st.subheader("Crime by Type")
        vc = df["crime_type"].value_counts().reset_index()
        vc.columns = ["crime_type", "count"]
        fig = px.bar(
            vc,
            x="crime_type",
            y="count",
            labels={"crime_type": "Crime Type", "count": "Count"},
            title="Crime Frequency by Type",
        )
        st.plotly_chart(fig, use_container_width=True)

    elif role == "analyst":
        st.success("Analyst View")
        st.subheader("Trend Over Time")

        # Add a selector for the time period
        period = st.radio(
            "Select trend interval", ["Daily", "Weekly", "Monthly"], index=0, horizontal=True
        )

        if period == "Daily":
            trend_df = df.groupby(df["date"].dt.date).size().reset_index(name="count")
            x_label = "Day"
        elif period == "Weekly":
            trend_df = df.groupby(df["date"].dt.to_period("W")).size().reset_index(name="count")
            trend_df["date"] = trend_df["date"].astype(str)
            x_label = "Week"
        elif period == "Monthly":
            trend_df = df.groupby(df["date"].dt.to_period("M")).size().reset_index(name="count")
            trend_df["date"] = trend_df["date"].astype(str)
            x_label = "Month"

        fig_trend = px.line(
            trend_df,
            x="date",
            y="count",
            title=f"Crime Trend ({period})",
            labels={"date": x_label, "count": "Crime Count"},
            markers=True,
        )
        st.plotly_chart(fig_trend, use_container_width=True)

    elif role == "law_enforcement":
        st.success("Law Enforcement View: Full Access")
        st.subheader("Raw Data")
        st.dataframe(df)

        # Crime Map differentiated by crime type
        st.subheader("Crime Map (Differentiated by Crime Type)")
        map_df = df.dropna(subset=["latitude", "longitude", "crime_type"])
        if not map_df.empty:
            fig_map = px.scatter_mapbox(
                map_df,
                lat="latitude",
                lon="longitude",
                color="crime_type",
                hover_name="crime_type",
                zoom=10,
                mapbox_style="carto-positron",
                title="Crime Incidents by Type",
            )
            st.plotly_chart(fig_map, use_container_width=True)
        else:
            st.info("No location data to display.")

        # Forecasting with confidence interval
        st.subheader("📈 Crime Forecast (Next 30 Days)")
        try:
            from prophet import Prophet

            ts = df.groupby(df["date"].dt.floor("d")).size().reset_index(name="y")
            ts.rename(columns={"date": "ds"}, inplace=True)
            ts = ts.sort_values("ds")

            if len(ts) < 2:
                st.warning("Not enough historical data to forecast.")
            else:
                model = Prophet()
                model.fit(ts)

                future = model.make_future_dataframe(periods=30)
                forecast = model.predict(future)

                fig_forecast = px.line(
                    forecast,
                    x="ds",
                    y="yhat",
                    labels={"ds": "Date", "yhat": "Predicted Crime Count"},
                    title="Forecast with Confidence Interval",
                )
                fig_forecast.add_traces(
                    [
                        dict(
                            x=list(forecast["ds"]) + list(forecast["ds"][::-1]),
                            y=list(forecast["yhat_upper"]) + list(forecast["yhat_lower"][::-1]),
                            fill="toself",
                            fillcolor="rgba(0,123,255,0.2)",
                            line=dict(color="rgba(255,255,255,0)"),
                            hoverinfo="skip",
                            name="Confidence Interval",
                        )
                    ]
                )
                fig_forecast.add_scatter(
                    x=ts["ds"], y=ts["y"], mode="markers+lines",
                    name="Historical", marker=dict(size=6)
                )
                st.plotly_chart(fig_forecast, use_container_width=True)
        except Exception as e:
            st.error(f"Forecasting failed: {e}")

        # Hotspot detection
        st.subheader("🔥 Crime Hotspot Detection")
        try:
            from sklearn.cluster import KMeans

            loc_df = df[["latitude", "longitude"]].dropna()
            if len(loc_df) >= 3:
                k = st.slider("Cluster count", 2, 8, 3)
                kmeans = KMeans(n_clusters=k, random_state=0)
                loc_df = loc_df.copy()
                loc_df["cluster"] = kmeans.fit_predict(loc_df)
                fig_hot = px.scatter_mapbox(
                    loc_df,
                    lat="latitude",
                    lon="longitude",
                    color="cluster",
                    zoom=10,
                    mapbox_style="carto-positron",
                    title="Crime Hotspots",
                )
                st.plotly_chart(fig_hot, use_container_width=True)
            else:
                st.warning("Need at least 3 points for hotspot detection.")
        except Exception as e:
            st.error(f"Hotspot detection error: {e}")

        # Report generation
        st.subheader("📄 Export Report")
        chart_paths = []
        vc = df["crime_type"].value_counts().reset_index()
        vc.columns = ["crime_type", "count"]
        bar_chart = px.bar(
            vc,
            x="crime_type",
            y="count",
            labels={"crime_type": "Crime Type", "count": "Count"},
            title="Crime Frequency by Type",
        )
        chart_paths.append(save_plotly_as_image(bar_chart))

        try:
            if "fig_forecast" in locals():
                chart_paths.append(save_plotly_as_image(fig_forecast))
        except Exception:
            pass

        if st.button("Download PDF Report"):
            pdf_bytes = generate_pdf_report(
                df, st.session_state.username, chart_paths
            )
            st.download_button("Download PDF", pdf_bytes, file_name="crime_report.pdf")

    st.markdown("## Summary Metrics")
    cols = st.columns(3)
    total_crimes = len(df)
    unique_types = df["crime_type"].nunique()
    date_span = f"{df['date'].min().date()} to {df['date'].max().date()}"
    cols[0].metric("Total Incidents", total_crimes)
    cols[1].metric("Crime Types", unique_types)
    cols[2].metric("Date Range", date_span)


# Main flow
if st.session_state.logged_in:
    show_dashboard()
else:
    show_login()

