# app.py - Crime Pattern Dashboard (full) with PDF unicode-safe export
import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
import json
import io
import os
import tempfile
import glob
from datetime import datetime
from fpdf import FPDF

from utils import authenticate_user, create_user  # your utils

st.set_page_config(page_title="Crime Pattern Dashboard", layout="wide", initial_sidebar_state="expanded")

# ---------------- Session state ----------------
if "logged_in" not in st.session_state:
    st.session_state.logged_in = False
if "username" not in st.session_state:
    st.session_state.username = ""
if "role" not in st.session_state:
    st.session_state.role = ""

# ---------------- Ensure users.json ----------------
USERS_FILE = "users.json"
if not os.path.exists(USERS_FILE):
    with open(USERS_FILE, "w") as f:
        json.dump({
            "users": [
                {"username": "public", "password": "public123", "role": "public"},
                {"username": "analyst", "password": "analyst123", "role": "analyst"},
                {"username": "law", "password": "law123", "role": "law_enforcement"}
            ]
        }, f, indent=2)


# ---------------- Helpers ----------------
def sanitize_for_pdf(text: str) -> str:
    """
    Replace common emoji with ASCII tokens and ensure the resulting string is latin-1 encodable.
    Uses 'replace' to substitute non-latin1 chars with '?' so FPDF won't crash.
    """
    if text is None:
        return ""
    try:
        # Replace common emojis we use in app with short words
        replacements = {
            "🚨": "[ALERT]",
            "📊": "[SPIKE]",
            "⚠️": "[WARN]",
            "⚠": "[WARN]",
            "📄": "[REPORT]",
            "🔥": "[HOTSPOT]",
            "✅": "[OK]",
            "→": "->",
            "–": "-",  # en-dash
            "—": "-",  # em-dash
        }
        for k, v in replacements.items():
            text = text.replace(k, v)
        # Finally ensure latin-1 safe encoding (replace unsupported chars with '?')
        safe = text.encode('latin-1', errors='replace').decode('latin-1')
        return safe
    except Exception:
        # If anything weird happens, strip to bytes-safe ascii fallback
        return str(text).encode('ascii', errors='replace').decode('ascii')


def save_plotly_as_image(fig):
    """Save Plotly figure to temp PNG using kaleido. Returns path or None."""
    try:
        tmp = tempfile.NamedTemporaryFile(delete=False, suffix=".png")
        tmp.close()
        # write_image may require kaleido; engine arg deprecated in future versions
        fig.write_image(tmp.name, format="png")
        return tmp.name
    except Exception as e:
        st.warning(f"Could not save chart image: {e}")
        try:
            if os.path.exists(tmp.name):
                os.remove(tmp.name)
        except Exception:
            pass
        return None


def cleanup_temp_images():
    """Remove temporary PNGs created in the system temp dir and current dir."""
    tmp_dir = tempfile.gettempdir()
    patterns = [os.path.join(tmp_dir, "*.png"), "*.png"]
    for patt in patterns:
        for p in glob.glob(patt):
            try:
                os.remove(p)
            except Exception:
                pass


def get_alerts(df, role):
    """Return a list of alert strings (plain text) based on df and role."""
    alerts = []
    if df is None or df.empty:
        return alerts
    try:
        if "crime_type" in df.columns:
            vc = df["crime_type"].value_counts()
            top_count = int(vc.max())
            top_type = vc.idxmax()
            if top_count > 50:
                alerts.append(f"🚨 High number of {top_type} incidents detected: {top_count} cases.")
    except Exception:
        pass

    try:
        if "date" in df.columns:
            last_7d = df[df["date"] >= pd.Timestamp.now() - pd.Timedelta(days=7)]
            if len(last_7d) > 0 and (len(last_7d) / max(1, len(df))) > 0.25:
                pct = int((len(last_7d) / max(1, len(df))) * 100)
                alerts.append(f"📊 {len(last_7d)} incidents reported in the last 7 days ({pct}% of records).")
    except Exception:
        pass

    if role == "law_enforcement":
        alerts.append("⚠️ System maintenance scheduled for Sunday midnight (01:00–03:00).")
    return alerts


def generate_pdf_report(df, username, chart_paths, alerts):
    """Create PDF bytes including header, alerts, summary counts and chart images.
       All strings are sanitized for latin-1 to avoid FPDF UnicodeEncodeError."""
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    pdf.set_font("Arial", "B", 16)
    title = sanitize_for_pdf("Crime Report Summary")
    pdf.cell(0, 10, title, ln=1, align="C")
    pdf.set_font("Arial", size=11)
    pdf.ln(2)

    byline = sanitize_for_pdf(f"Generated by: {username}")
    pdf.cell(0, 8, byline, ln=1)
    date_line = sanitize_for_pdf(f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    pdf.cell(0, 8, date_line, ln=1)
    pdf.ln(4)

    # Alerts
    if alerts:
        pdf.set_font("Arial", "B", 12)
        pdf.cell(0, 8, sanitize_for_pdf("Alerts & Notifications:"), ln=1)
        pdf.set_font("Arial", size=11)
        for a in alerts:
            pdf.multi_cell(0, 6, sanitize_for_pdf(f"- {a}"))
        pdf.ln(4)

    # Crime counts summary
    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 8, sanitize_for_pdf("Crime Type Counts:"), ln=1)
    pdf.set_font("Arial", size=11)
    try:
        summary = df["crime_type"].value_counts().reset_index()
        summary.columns = ["crime_type", "count"]
        for _, row in summary.iterrows():
            crime = sanitize_for_pdf(str(row["crime_type"]))
            count = int(row["count"])
            pdf.cell(0, 6, sanitize_for_pdf(f"{crime}: {count}"), ln=1)
        pdf.ln(4)
    except Exception:
        pdf.cell(0, 6, sanitize_for_pdf("No crime type summary available."), ln=1)
        pdf.ln(4)

    # Add chart images
    for path in chart_paths:
        if path and os.path.exists(path):
            try:
                pdf.image(path, w=180)
                pdf.ln(5)
            except Exception:
                # skip images that cause issues
                pass

    # write to temp pdf and return bytes
    tmp_pdf = tempfile.NamedTemporaryFile(delete=False, suffix=".pdf")
    tmp_pdf.close()
    pdf.output(tmp_pdf.name)
    with open(tmp_pdf.name, "rb") as f:
        pdf_bytes = f.read()
    # cleanup pdf file
    try:
        os.remove(tmp_pdf.name)
    except Exception:
        pass
    return pdf_bytes


# ---------------- Login / Signup ----------------
def show_login():
    st.markdown(
        """
        <div style="max-width:480px; margin:auto; padding:1.6rem; background:#2A2A33; border-radius:12px; box-shadow:0 10px 30px rgba(0,0,0,0.08);">
          <h2 style="text-align:center; color:FFFFFF; margin-bottom:4px;">Login</h2>
          <p style="text-align:center; color:FFFFFF; margin-top:-6px; font-size:13px;">Enter credentials to access the dashboard</p>
        </div>
        """,
        unsafe_allow_html=True,
    )

    col1, col2, col3 = st.columns([1, 2, 1])
    with col2:
        username = st.text_input("Username")
        password = st.text_input("Password", type="password")
        role_select = st.selectbox("Role", ["public", "analyst", "law_enforcement"])
        if st.button("Login"):
            role = authenticate_user(username, password)
            if role and role == role_select:
                st.session_state.logged_in = True
                st.session_state.username = username
                st.session_state.role = role
                st.success(f"Logged in as {username} ({role})")
                try:
                    st.experimental_rerun()
                except Exception:
                    pass
            else:
                st.error("Invalid credentials or role mismatch.")

    st.markdown("---")
    st.subheader("New User Signup")
    new_username = st.text_input("New Username", key="signup_user")
    new_password = st.text_input("New Password", type="password", key="signup_pass")
    new_role = st.selectbox("Select Role", ["public", "analyst", "law_enforcement"], key="signup_role")

    if st.button("Sign Up"):
        if not new_username or not new_password:
            st.warning("Provide both username and password.")
        else:
            success = create_user(new_username, new_password, new_role)
            if success:
                st.success("Account created. Please log in.")
            else:
                st.error("Username already exists.")


# ---------------- Dashboard ----------------
def show_dashboard():
    role = st.session_state.role
    username = st.session_state.username

    st.sidebar.markdown(f"**Logged in as:** {username} ({role})")
    if st.sidebar.button("Logout"):
        st.session_state.logged_in = False
        st.session_state.username = ""
        st.session_state.role = ""
        try:
            st.experimental_rerun()
        except Exception:
            pass
        return

    st.title("🚔 Crime Pattern Analysis Dashboard")
    st.markdown("Upload a CSV or Excel file containing columns: `date`, `crime_type`, `latitude`, `longitude` (optional: region/city/district).")

    uploaded_file = st.file_uploader("Upload Crime Data File (CSV or Excel)", type=["csv", "xlsx", "xls"])
    if uploaded_file is None:
        st.info("Please upload a CSV or Excel file with columns: date, crime_type, latitude, longitude.")
        return

    # Load file
    try:
        fname = uploaded_file.name.lower()
        if fname.endswith(".csv"):
            raw_df = pd.read_csv(uploaded_file)
        else:
            raw_df = pd.read_excel(uploaded_file)
    except Exception as e:
        st.error(f"Failed to read file: {e}")
        return

    raw_df.columns = raw_df.columns.str.lower().str.strip()
    required = {"date", "crime_type", "latitude", "longitude"}
    if not required.issubset(set(raw_df.columns)):
        st.error(f"File must contain columns: {', '.join(required)}. Found: {list(raw_df.columns)}")
        return

    # Show raw preview and stats
    st.markdown("### Raw Data Preview")
    st.dataframe(raw_df.head(20), use_container_width=True)

    raw_stats = {
        "Rows": int(len(raw_df)),
        "Columns": list(raw_df.columns),
        "Duplicate Rows": int(raw_df.duplicated().sum()),
        "Missing Dates": int(raw_df["date"].isnull().sum()),
        "Missing Latitudes": int(raw_df["latitude"].isnull().sum()),
        "Missing Longitudes": int(raw_df["longitude"].isnull().sum())
    }
    st.markdown("**Raw Data Stats**")
    st.write(raw_stats)

    # Cleaning
    df = raw_df.copy()
    df = df.drop_duplicates().reset_index(drop=True)
    try:
        df["date"] = pd.to_datetime(df["date"], errors="coerce")
    except Exception:
        pass
    df = df.dropna(subset=["date", "latitude", "longitude", "crime_type"]).reset_index(drop=True)

    st.markdown("### Cleaned Data Preview")
    st.dataframe(df.head(20), use_container_width=True)

    clean_stats = {
        "Rows": int(len(df)),
        "Columns": list(df.columns),
        "Duplicate Rows": int(df.duplicated().sum()),
        "Missing Dates": int(df["date"].isnull().sum()) if "date" in df.columns else 0,
        "Missing Latitudes": int(df["latitude"].isnull().sum()) if "latitude" in df.columns else 0,
        "Missing Longitudes": int(df["longitude"].isnull().sum()) if "longitude" in df.columns else 0
    }
    st.markdown("**Cleaned Data Stats**")
    st.write(clean_stats)

    diff_stats = {
        "Rows Removed": raw_stats["Rows"] - clean_stats["Rows"],
        "Duplicates Removed": raw_stats["Duplicate Rows"],
        "Rows with Missing Key Columns Removed": raw_stats["Rows"] - (clean_stats["Rows"] + raw_stats["Duplicate Rows"])
    }
    st.markdown("**Data Cleaning Summary**")
    st.write(diff_stats)

    # Sidebar filters
    st.sidebar.header("Filters")
    crime_types = sorted(df["crime_type"].dropna().unique().tolist())
    selected_types = st.sidebar.multiselect("Crime Type", crime_types, default=crime_types)
    if selected_types:
        df = df[df["crime_type"].isin(selected_types)]

    # Date range
    if "date" in df.columns and not df.empty:
        try:
            min_date = df["date"].min().date()
            max_date = df["date"].max().date()
            date_range = st.sidebar.date_input("Date Range", [min_date, max_date])
            if isinstance(date_range, (list, tuple)) and len(date_range) == 2:
                start, end = date_range
                df = df[(df["date"].dt.date >= start) & (df["date"].dt.date <= end)]
        except Exception:
            pass

    # Hour
    if "date" in df.columns and not df.empty:
        df["hour"] = df["date"].dt.hour
        hour_range = st.sidebar.slider("Hour Range (0–23)", 0, 23, (0, 23), step=1)
        df = df[(df["hour"] >= hour_range[0]) & (df["hour"] <= hour_range[1])]
        avail_hours = sorted(df["hour"].dropna().unique().tolist())
        st.sidebar.caption(f"Available hours after filters: {avail_hours}" if avail_hours else "No records in selected hour range.")

    # Region filter or grid
    region_cols = [c for c in df.columns if c.lower() in ["region", "city", "district"]]
    if region_cols:
        region_col = region_cols[0]
        region_vals = sorted(df[region_col].dropna().unique().tolist())
        selected_regions = st.sidebar.multiselect("Region", region_vals, default=region_vals)
        if selected_regions:
            df = df[df[region_col].isin(selected_regions)]
    else:
        st.sidebar.markdown("**Region (derived from Lat/Lon grid)**")
        grid_size = st.sidebar.slider("Grid size (degrees)", 0.01, 0.5, 0.05, 0.01)
        lat_bin = np.round(df["latitude"] / grid_size) * grid_size
        lon_bin = np.round(df["longitude"] / grid_size) * grid_size
        df["region_grid"] = lat_bin.round(4).astype(str) + "," + lon_bin.round(4).astype(str)
        grid_regions = sorted(df["region_grid"].dropna().unique().tolist())
        selected_grids = st.sidebar.multiselect("Region (grid)", grid_regions, default=grid_regions)
        if selected_grids:
            df = df[df["region_grid"].isin(selected_grids)]

    if df.empty:
        st.warning("No data matches the selected filters. Try expanding selections.")
        return

    # Alerts
    alerts = get_alerts(df, role)
    if alerts:
        st.markdown("## 🚨 Alerts & Notifications")
        for a in alerts:
            st.warning(a)

    chart_paths = []

    # Role-specific views
    if role == "public":
        st.info("Public View: Aggregated summary")
        vc = df["crime_type"].value_counts().reset_index()
        vc.columns = ["crime_type", "count"]
        fig_bar = px.bar(vc, x="crime_type", y="count", title="Crime Frequency by Type", labels={"crime_type": "Crime Type", "count": "Count"})
        st.plotly_chart(fig_bar, use_container_width=True)
        p = save_plotly_as_image(fig_bar)
        if p:
            chart_paths.append(p)

    elif role == "analyst":
        st.success("Analyst View")
        period = st.radio("Granularity", ["Daily", "Weekly", "Monthly"], index=0, horizontal=True)
        if period == "Daily":
            trend_df = df.groupby(df["date"].dt.date).size().reset_index(name="count")
            trend_df.rename(columns={"date": "ds"}, inplace=True)
            xcol = trend_df.columns[0]
        elif period == "Weekly":
            trend_df = df.groupby(df["date"].dt.to_period("W")).size().reset_index(name="count")
            trend_df["date"] = trend_df["date"].astype(str)
            xcol = "date"
        else:
            trend_df = df.groupby(df["date"].dt.to_period("M")).size().reset_index(name="count")
            trend_df["date"] = trend_df["date"].astype(str)
            xcol = "date"

        fig_trend = px.line(trend_df, x=xcol, y="count", markers=True, title=f"Crime Trend ({period})")
        fig_trend.update_layout(xaxis_title=period, yaxis_title="Incidents")
        st.plotly_chart(fig_trend, use_container_width=True)
        p = save_plotly_as_image(fig_trend)
        if p:
            chart_paths.append(p)

        # Hour vs Crime heat table
        st.subheader("Hourly Heatmap by Crime Type (counts)")
        try:
            heat_df = df.groupby([df["hour"], df["crime_type"]]).size().reset_index(name="count")
            heat_pivot = heat_df.pivot_table(index="hour", columns="crime_type", values="count", fill_value=0)
            st.dataframe(heat_pivot)
        except Exception:
            st.info("Not enough data for heatmap.")

    elif role == "law_enforcement":
        st.success("Law Enforcement View")
        st.subheader("Filtered Raw Data")
        st.dataframe(df, use_container_width=True)

        # Map
        st.subheader("Crime Incidents Map")
        try:
            map_df = df.dropna(subset=["latitude", "longitude"])
            if not map_df.empty:
                fig_map = px.scatter_mapbox(map_df, lat="latitude", lon="longitude", color="crime_type", hover_name="crime_type",
                                            zoom=10, mapbox_style="carto-positron", title="Crime Incidents by Type", height=500)
                st.plotly_chart(fig_map, use_container_width=True)
                p = save_plotly_as_image(fig_map)
                if p:
                    chart_paths.append(p)
            else:
                st.info("No geolocation data to plot.")
        except Exception as e:
            st.error(f"Map error: {e}")

        # Forecasting with Prophet
        st.subheader("📈 Crime Forecast (Next 30 days)")
        try:
            from prophet import Prophet
            ts = df.groupby(df["date"].dt.floor("d")).size().reset_index(name="y")
            ts.rename(columns={"date": "ds"}, inplace=True)
            ts = ts.sort_values("ds")
            if len(ts) < 2:
                st.warning("Not enough daily history to forecast (need at least 2 days).")
            else:
                model = Prophet()
                model.fit(ts)
                future = model.make_future_dataframe(periods=30)
                forecast = model.predict(future)

                fig_fore = px.line(forecast, x="ds", y="yhat", labels={"ds": "Date", "yhat": "Predicted"}, title="Forecast (yhat)")
                fig_fore.add_traces([
                    dict(
                        x=list(forecast["ds"]) + list(forecast["ds"][::-1]),
                        y=list(forecast["yhat_upper"]) + list(forecast["yhat_lower"][::-1]),
                        fill="toself",
                        fillcolor="rgba(0,123,255,0.15)",
                        line=dict(color="rgba(255,255,255,0)"),
                        hoverinfo="skip",
                        name="Confidence Interval"
                    )
                ])
                merged = forecast.merge(ts, left_on="ds", right_on="ds", how="left")
                if "y" in merged.columns and merged["y"].notnull().any():
                    fig_fore.add_scatter(x=merged["ds"], y=merged["y"], mode="markers+lines", name="Actual")
                st.plotly_chart(fig_fore, use_container_width=True)
                p = save_plotly_as_image(fig_fore)
                if p:
                    chart_paths.append(p)
        except Exception as e:
            st.error(f"Forecasting failed: {e}")

        # Hotspot detection
        st.subheader("🔥 Crime Hotspot Detection (KMeans)")
        try:
            from sklearn.cluster import KMeans
            loc_df = df[["latitude", "longitude"]].dropna()
            if len(loc_df) < 3:
                st.warning("Need at least 3 points for hotspot detection.")
            else:
                max_k = min(12, max(2, len(loc_df)//2))
                default_k = min(3, max_k)
                k = st.slider("Clusters (k)", 2, max_k, default_k)
                kmeans = KMeans(n_clusters=k, random_state=42)
                loc_df = loc_df.copy()
                loc_df["cluster"] = kmeans.fit_predict(loc_df)
                fig_hot = px.scatter_mapbox(loc_df, lat="latitude", lon="longitude", color="cluster", title="Hotspots (KMeans)", mapbox_style="carto-positron", zoom=10, height=500)
                st.plotly_chart(fig_hot, use_container_width=True)
                p = save_plotly_as_image(fig_hot)
                if p:
                    chart_paths.append(p)
        except Exception as e:
            st.error(f"Hotspot detection error: {e}")

        # Export PDF
        st.subheader("📄 Export Report (PDF)")
        include_charts = st.checkbox("Include charts in PDF", value=True)
        if st.button("Generate PDF Report"):
            pdf_bytes = generate_pdf_report(df, username, chart_paths if include_charts else [], alerts)
            # cleanup temp pngs after embedding
            cleanup_temp_images()
            st.download_button("Download Report (PDF)", data=pdf_bytes, file_name=f"crime_report_{username}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf", mime="application/pdf")

    # Summary Metrics
    st.markdown("## Summary Metrics")
    cols = st.columns(3)
    try:
        total = len(df)
        unique_ct = int(df["crime_type"].nunique())
        ds_min = df["date"].min().date()
        ds_max = df["date"].max().date()
        cols[0].metric("Total Incidents", total)
        cols[1].metric("Crime Types", unique_ct)
        cols[2].metric("Date Range", f"{ds_min} - {ds_max}")
    except Exception:
        cols[0].metric("Total Incidents", "—")
        cols[1].metric("Crime Types", "—")
        cols[2].metric("Date Range", "—")


# ---------------- Entrypoint ----------------
def main():
    if st.session_state.logged_in:
        show_dashboard()
    else:
        show_login()


if __name__ == "__main__":
    main()
